<a href="https://colab.research.google.com/github/Roopalsood/Customer_Retail_Behaviour_Analysis/blob/main/Customer_Retail_Behaviour_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd

Loading data and performing Exploratory Data Analysis.

In [40]:
url = 'https://raw.githubusercontent.com/amlanmohanty1/customer-trends-data-analysis-SQL-Python-PowerBI/refs/heads/main/customer_shopping_behavior.csv'
df = pd.read_csv(url)

In [41]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [42]:
df.describe(include ='all') # by default gives only numerical col so add include = 'all'

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [43]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

This line fills missing values (NaN) in the Review Rating column using the median review rating of each category. Example:- Electronics, clothing etc.

This code groups the dataframe by Category and selects the Review Rating column for each group.
Using transform(), it fills missing (NaN) review ratings with the median rating of that specific category while keeping the original dataframe structure intact.

In [44]:
df['Review Rating'] =df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [45]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [46]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

pd.qcut is used to divide the whole data set in quantiles and here we are dividing it in 4 parts with same number of observation.
pd.cut simply divides in 4 equal parts.

In [47]:
#creating a new column age_group from age

labels = ['Young-Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [48]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young-Adult
2   50  Middle-aged
3   21  Young-Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young-Adult
8   26  Young-Adult
9   57  Middle-aged

In [49]:
#create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Bi-weekly': 14,
    'Monthly': 30,
    'Quaterly': 90,
    'Annually': 365,
    'Every 3 months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [50]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [51]:
df[['discount_applied', 'promo_code_used']].head(10) #one is redundant

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [52]:
(df['discount_applied'] == df['promo_code_used']).all() #to check if the column is actually redundant

np.True_

Axis specfies the direction
axis=0	Rows
axis=1	Columns

In [53]:
df = df.drop('promo_code_used', axis = 1)

In [54]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [55]:
import sqlite3

This code establishes a connection to an SQLite database file named `customer_data.db`. If the file doesn't exist, `sqlite3.connect()` will create it. The `cursor` object is used to execute SQL commands.

In [56]:
conn = sqlite3.connect('customer_data.db')
cursor = conn.cursor()

print("Successfully connected to SQLite database!")

Successfully connected to SQLite database!

In [57]:
df.to_sql('customers', conn, if_exists='replace', index=False)
print("DataFrame 'df' successfully inserted into 'customers' table.")

conn.commit()

cursor.execute("SELECT * FROM customers LIMIT 5")

rows = cursor.fetchall()

print("\n--- First 5 rows from 'customers' table after df insertion ---")
for row in rows:
    print(row)

DataFrame 'df' successfully inserted into 'customers' table.

--- First 5 rows from 'customers' table after df insertion ---
(1, 55, 'Male', 'Blouse', 'Clothing', 53, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 14, 'Venmo', 'Fortnightly', 'Middle-aged', 14.0)
(2, 19, 'Male', 'Sweater', 'Clothing', 64, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 2, 'Cash', 'Fortnightly', 'Young-Adult', 14.0)
(3, 50, 'Male', 'Jeans', 'Clothing', 73, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 23, 'Credit Card', 'Weekly', 'Middle-aged', 7.0)
(4, 21, 'Male', 'Sandals', 'Footwear', 90, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 49, 'PayPal', 'Weekly', 'Young-Adult', 7.0)
(5, 45, 'Male', 'Blouse', 'Clothing', 49, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 31, 'PayPal', 'Annually', 'Middle-aged', 365.0)

Business analysis using SQL.

In [58]:
# import os

# os.listdir()

In [59]:
# from google.colab import files

# files.download('customer_data.db')

In [60]:
# ================================
# Q1. Total Revenue by Gender
# ================================

query = """
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender
"""

result = pd.read_sql_query(query, conn)

result

   gender  revenue
0  Female    75191
1    Male   157890

In [61]:
# ================================
# Q2. Customers Using Discount But Spending Above Average
# ================================

query = """
SELECT customer_id,
       purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customers
)
"""

result = pd.read_sql_query(query, conn)

result

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [62]:
# ================================
# Q3. Top 5 Products with Highest Average Review Rating
# ================================

query = """
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5
"""

result = pd.read_sql_query(query, conn)

result

  item_purchased  average_product_rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

In [63]:
# ================================
# Q4. Average Purchase Amount:
# Standard vs Express Shipping
# ================================

query = """
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS average_purchase
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
"""

result = pd.read_sql_query(query, conn)

result

  shipping_type  average_purchase
0       Express             60.48
1      Standard             58.46

In [64]:
# ================================
# Q5. Subscriber vs Non-Subscriber Spending
# ================================

query = """
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC
"""

result = pd.read_sql_query(query, conn)

result

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [65]:
# ================================
# Q6. Top 5 Products with Highest Discount Usage %
# ================================

query = """
SELECT item_purchased,
       ROUND(
           100.0 * SUM(
               CASE
                   WHEN discount_applied = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*),
       2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5
"""

result = pd.read_sql_query(query, conn)

result

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [66]:
# ================================
# Q7. Customer Segmentation
# ================================

query = """
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customers
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
"""

result = pd.read_sql_query(query, conn)

result

  customer_segment  number_of_customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [67]:
# ================================
# Q8. Top 3 Products Within Each Category
# ================================

query = """
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3
"""

result = pd.read_sql_query(query, conn)

result

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [68]:
# ================================
# Q9. Repeat Buyers and Subscription Status
# ================================

query = """
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status
"""

result = pd.read_sql_query(query, conn)

result

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [69]:
# ================================
# Q9. Repeat Buyers and Subscription Status
# ================================

query = """
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status
"""

result = pd.read_sql_query(query, conn)

result

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [70]:
# ================================
# Q10. Revenue Contribution by Age Group
# ================================

query = """
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC
"""

result = pd.read_sql_query(query, conn)

result

     age_group  total_revenue
0  Young-Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763

In [71]:
# Closing connection
conn.close()
print("Connection closed.")

Connection closed.